set nocompatible " be iMproved, required
syntax enable " enable syntax processing 
filetype on " filetype detection disabled to allow vundle to work 
filetype indent on

set t_vb= "set NO beeps nor flashes 
" set tw=99 " set text width to 79 characters
set expandtab " tabs are now spaces!!
set tabstop=4 " number of visual spaces per TAB
set softtabstop=4 " number of spaces in tab when editing
set shiftwidth=4 " indentation space
set background=dark  
colorscheme solarized  "sets the solarized color scheme available in ~(.vim/colors/
set spell spelllang=en_us " enables spelling check in english
" set nospell
"set history=1000 " default is very low
set number " shows line numbers
set showcmd " shows command in bottom bat altho useless if poweline plugin is used 
set cursorline " highlights current line 
set wildmenu " visual autocomplete for command menu
set showmatch " higlights matching parenthesis 
set incsearch " searches as characters are entered
set hlsearch " highlights matches
set ignorecase
set smartcase "search case-sensitive smart
set encoding=utf-8
set sidescroll=10 sidescrolloff=10
set scrolloff=4
" Dispplay line number relative to the current line
set relativenumber
set number 
set undofile "persistant undo even if I quit vim
" when yanking automatically put text in clipboard
set clipboard=autoselect,unnamed
" make j and k go through wrapped lines
nnoremap j gj
nnoremap k gk
map <F1> :make
map <F2> :NERDTree


"set separate location for swap and 
set backupdir=~/.vim/tmp/
set directory=~/.vim/tmp/


" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'
"Plugin 'Valloric/YouCompleteMe'
"Plugin 'xolox/vim-easytags'
"Plugin 'xolox/vim-misc'
Plugin 'scrooloose/nerdtree.git'
"Plugin 'tomtom/tcomment_vim'
Plugin 'msanders/snipmate.vim.git'
Plugin 'jiangmiao/auto-pairs.git'
Plugin 'tpope/vim-surround'
Plugin 'vim-perl/vim-perl'
"Plugin 'scrooloose/syntastic'
"Plugin 'scrooloose/nerdcommenter'
"Plugin 'vim-latex/vim-latex'
Plugin 'ervandew/supertab'
"
"" The following are examples of different formats supported.
"" Keep Plugin commands between vundle#begin/end.
"" plugin on GitHub repo
"        " Plugin 'tpope/vim-fugitive'
"" plugin from http://vim-scripts.org/vim/scripts.html
"        " Plugin 'git://git.wincent.com/command-t.git'
"
"" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
"" To ignore plugin indent changes, instead use:
""filetype plugin on
""
"" Brief help
"" :PluginList       - lists configured plugins
"" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
"" :PluginSearch foo - searches for foo; append `!` to refresh local cache
"" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
""
"" see :h vundle for more details or wiki for FAQ
"" Put your non-Plugin stuff after this line
